name: Build

on:
  push:
    branches: [ "main" ]
    paths: [ "*.py" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: build
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        python: [ "3.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build app
        run: |
          pyinstaller -F -i main.ico -n ${{ vars.NAME }} main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.NAME }}-${{ matrix.os }}
          path: dist/*
